
#DB configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.properties.hibernate.format_sql=true

#spring.flyway.enabled=false
my.variable=dev

# Only include properties that differ from main config
#spring.jpa.hibernate.ddl-auto=validate

# Use this only if you have these env variables set
# spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}